### ISSUE TITLE
你好,我用select input-select不能触发$scope的函数是怎么回事啊?

### ISSUE THREAD

**Issue by Wjp43045** [chenjia/lxtIonic#2]
`<label class="item item-input item-icon-right" style="border-color: #fff;padding: 0px;">
    <span class="input-label">
        所在房间:
    </span>
    <select input-select ng-model="data.group.roomid" select-data="data.roomlist" option-text="name" option-value="id" prefix="" suffix="" circular="true" ng-click="ChangeRoom(id)"></select>
    <i class="icon ion-ios-arrow-down"></i>
</label>`
函数ChangeRoom触发不到, 很纠结

**Comment by chenjia** [comment]
我会更新示例，请查看最新的代码。
